### ISSUE TITLE
[Bug] East and West Directions are flipped

### ISSUE THREAD

**Issue by RyanCR03** [Qendolin/map-compass#1]
Whenever the player is facing east it shows facing west and whenever the player is facing west it shows facing east

**Comment by Qendolin** [comment]
But that's how compasses work, isn't it?

**Comment by Qendolin** [comment]
http://www.compassdude.com/compass-reading.php#:~:text=This%20is%20a%20very%20common%20mistake!

**Comment by Qendolin** [comment]
I'll add an option to reverse the labels

**Comment by Qendolin** [comment]
Added option in release 1.0.1
