### ISSUE TITLE
suggestion: compass on map

### ISSUE THREAD

**Issue by KaspianDev** [Qendolin/map-compass#2]
![obraz](https://user-images.githubusercontent.com/34658474/150211780-e9c98474-f20c-4121-92dc-3bf5a4ae3bdf.png)
like on image

**Comment by Qendolin** [comment]
Should I just add an x/y offset slider?

**Comment by KaspianDev** [comment]
yep that would be nice :)

**Comment by Qendolin** [comment]
Done https://modrinth.com/mod/map-compass/version/LbHtBN37
