### ISSUE TITLE
Update to 1.19.4, 1.20.1

### ISSUE THREAD

**Issue by Nukecraft5419** [Qendolin/map-compass#5]

**Comment by Qendolin** [comment]
Totally forgot about this 😅.
Here for 1.19.4: https://modrinth.com/mod/map-compass/version/1.1.1+1.19.4
Gonna update to 1.20 tomorrow maybe 

Edit: The build 1.1.0 yesterday was broken

**Comment by Nukecraft5419** [comment]
As a weight on the client and little or a lot, I have it makes sense to make it a resource pack to make it lighter

**Comment by Qendolin** [comment]
I'm sorry, I don't understand what you are trying to tell me. If you are using a translator then maybe try https://www.deepl.com/translator , from my experience it is excellent

**Comment by Qendolin** [comment]
For 1.20.1 : https://modrinth.com/mod/map-compass/version/1.2.0+1.20.1

**Comment by Nukecraft5419** [comment]
That one I use as a translator basically I wanted to know if it weighs a lot as a mod, and if there is in lighter alternative like Texture pack

**Comment by Qendolin** [comment]
Oh, well I can assure you that the mod is very performant and this is not possible with a just texture pack.

**Comment by Nukecraft5419** [comment]
https://github.com/LifeMC-Studios/LifeMC/issues/271
